version: '3.9'

services:
  backend:
    platform: linux/x86_64/v8
    build: ./labseq-api
    container_name: labseq-api
    ports:
      - 8080:8080

  frontend:
    build: ./labseq-ui
    container_name: labseq-ui
    ports:
      - 4200:80